# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_gen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_gen.proto',
  package='myproto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63lient_gen.proto\x12\x07myproto*Z\n\x02ID\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0bMsg_PingREQ\x10\xe8\x07\x12\x10\n\x0bMsg_PingACK\x10\xe9\x07\x12\x12\n\rMsg_VerifyREQ\x10\xea\x07\x12\x12\n\rMsg_VerifyACK\x10\xeb\x07\x62\x06proto3'
)

_ID = _descriptor.EnumDescriptor(
  name='ID',
  full_name='myproto.ID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Msg_PingREQ', index=1, number=1000,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Msg_PingACK', index=2, number=1001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Msg_VerifyREQ', index=3, number=1002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Msg_VerifyACK', index=4, number=1003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=29,
  serialized_end=119,
)
_sym_db.RegisterEnumDescriptor(_ID)

ID = enum_type_wrapper.EnumTypeWrapper(_ID)
NONE = 0
Msg_PingREQ = 1000
Msg_PingACK = 1001
Msg_VerifyREQ = 1002
Msg_VerifyACK = 1003


DESCRIPTOR.enum_types_by_name['ID'] = _ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
