// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: client_gen.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Myproto {

  /// <summary>Holder for reflection information generated from client_gen.proto</summary>
  public static partial class ClientGenReflection {

    #region Descriptor
    /// <summary>File descriptor for client_gen.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientGenReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBjbGllbnRfZ2VuLnByb3RvEgdteXByb3RvKloKAklEEggKBE5PTkUQABIQ",
            "CgtNc2dfUGluZ1JFURDoBxIQCgtNc2dfUGluZ0FDSxDpBxISCg1Nc2dfVmVy",
            "aWZ5UkVREOoHEhIKDU1zZ19WZXJpZnlBQ0sQ6wdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Myproto.ID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ID {
    [pbr::OriginalName("NONE")] None = 0,
    /// <summary>
    /// client_login.proto
    /// </summary>
    [pbr::OriginalName("Msg_PingREQ")] MsgPingReq = 1000,
    [pbr::OriginalName("Msg_PingACK")] MsgPingAck = 1001,
    [pbr::OriginalName("Msg_VerifyREQ")] MsgVerifyReq = 1002,
    [pbr::OriginalName("Msg_VerifyACK")] MsgVerifyAck = 1003,
  }

  #endregion

}

#endregion Designer generated code
