# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_gen.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lient_gen.proto\x12\tProtosIds*a\n\tProtosIds\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0bMsg_PingREQ\x10\xe8\x07\x12\x10\n\x0bMsg_PingACK\x10\xe9\x07\x12\x12\n\rMsg_VerifyREQ\x10\xea\x07\x12\x12\n\rMsg_VerifyACK\x10\xeb\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_gen_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROTOSIDS']._serialized_start=31
  _globals['_PROTOSIDS']._serialized_end=128
# @@protoc_insertion_point(module_scope)
