# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lient_login.proto\x12\x07myproto\x1a\x0c\x63ommon.proto\"\t\n\x07PingREQ\"?\n\x07PingACK\x12 \n\x03Ret\x18\x01 \x01(\x0e\x32\x13.myproto.ResultCode\x12\x12\n\nServerTime\x18\x02 \x01(\x03\".\n\tVerifyREQ\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"-\n\tVerifyACK\x12 \n\x03Ret\x18\x01 \x01(\x0e\x32\x13.myproto.ResultCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_login_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQ']._serialized_start=45
  _globals['_PINGREQ']._serialized_end=54
  _globals['_PINGACK']._serialized_start=56
  _globals['_PINGACK']._serialized_end=119
  _globals['_VERIFYREQ']._serialized_start=121
  _globals['_VERIFYREQ']._serialized_end=167
  _globals['_VERIFYACK']._serialized_start=169
  _globals['_VERIFYACK']._serialized_end=214
# @@protoc_insertion_point(module_scope)
